name: Build ai2/papgergym-orchestrator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    # Run this workflow anytime anytime these paths update 
    # (+ anytime there's a new release tag for this image)
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.github/workflows'
      - 'pyproject.toml'
    branches:
      - main
  workflow_dispatch:  # allow manual triggers on GitHub UI
    inputs:
      run_build:
        description: 'Build image'
        type: boolean
        default: true

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04 # ubuntu-latest
    timeout-minutes: 60
    if: (github.event_name != 'workflow_run' && (github.event_name != 'workflow_dispatch' || inputs.run_build)) || (github.event.workflow_run.conclusion == 'success')
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          beaker_token: ${{ secrets.BEAKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure
          install: true

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: papergym:latest
          load: true
          pull: true
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Push image
        uses: ./.github/actions/push
        with:
          image: papergym  # tag of the image we built in the previous step
          beaker: papgergym-orchestrator  # name of the image on Beaker
          latest: true  # label this image as the 'latest'

      - name: Test image
        uses: ./.github/actions/test
        with:
          beaker: papgergym-orchestrator  # name of the image on Beaker
